name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        uses: ChenPi11/ci-test@main
      - name: Test
        run: |
          ${{steps.setup.outputs.pkgname}}
          

