name: Win codeserver

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up MinGW
      uses: e-t-l/setup-mingw@master
      with:
        platform: x64
        static: 1

    - name: Install
      run: |
        sh npm install node-addon-api
        sh npm install code-server
        dir
        code-server
