name: Win codeserver

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Set up MinGW
      uses: e-t-l/setup-mingw@master
      with:
        platform: x64
        static: 1

    - name: Install Tor
      run: |
        New-item -ItemType directory C:\tmp\hidden_service
        New-item -ItemType directory tor
        cd tor
        tar zxvf ../tor-expert-bundle-windows-x86_64-14.0.4.tar.gz
        cd ..

    - name: Install code-server
      shell: sh
      run: |
        npm install node-addon-api
        npm install code-server

    - name: Pack code-server
      run: |
        ls
        cd ..
        tar zcvf ci-test.tar.gz ci-test
        cd ci-test
        mv ../ci-test.tar.gz .
  
    - name: Run
      run: |
        npx code-server
        ./readlog.ps1
